# Generated by Django 4.2.6 on 2023-10-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_wallet_user'),
    ]

    operations = [
    ]
