# Generated by Django 4.2.6 on 2023-10-31 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20231030_2128'),
        ('budget', '0004_expense_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_for_user', to='profiles.userprofile'),
        ),
    ]
